FROM traviswheelerlab/mirage-build AS build

RUN mkdir /mirage
WORKDIR /mirage

COPY CMakeLists.txt ./
COPY src ./src
COPY dependencies ./dependencies
RUN ls -la .

RUN cmake . && \
    make

FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
        perl \
        rsync \
        wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /mirage/build /opt/mirage
ENV PATH=$PATH:/opt/mirage

