FROM traviswheelerlab/mirage-build AS build

ADD . /code
WORKDIR /code
RUN rm -f CMakeCache.txt
RUN cmake . && \
    make && \
    make build-dependencies && \
    make build-perl && \
    make build-shell

FROM debian:bullseye-slim

COPY --from=build /code/build /code
ENV PATH=$PATH:/code
