FROM traviswheelerlab/mirage-build AS build

ADD . /mirage
WORKDIR /mirage
RUN rm -f CMakeCache.txt
RUN cmake . && \
    make

FROM debian:bullseye-slim

COPY --from=build /mirage/build /opt/mirage
ENV PATH=$PATH:/opt/mirage
