FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
        cmake \
        gcc \
        make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

VOLUME /code
WORKDIR /code
