name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: traviswheelerlab/mirage-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: cmake . && make
